@echo off
echo Waiting for PostgreSQL...
timeout /t 5

echo Applying database migrations...
alembic upgrade head

echo Starting FastAPI application...
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload